### ISSUE TITLE
all usb 3.0 port can not read usb 2.0 devices，please help ！

### ISSUE THREAD

**Issue by vivikuyo** [l0ui3/hackintosh-skylake-z170#1]
hello!!
Im your fans,my mainboard  same as yours,and i use your 11.1 efi,today I update os to 11.3,and update some kext to the new version,every things looks ok,but all usb 3.0 port can not Identify usb 2.0 devices，I dont know how to figure out,please help！thank you very much!

**Comment by vivikuyo** [comment]
i try to update oc to 0.6.8, and resetnvram ,the usb 3.0 port worked,it identify usb 2.0 devices.

**Comment by l0ui3** [comment]
Great to know that, thanks for the test.
